#!/bin/bash
# Helper script to guide user through auth key setup

echo "🔐 Tailscale Auth Key Setup"
echo "=========================="
echo ""
echo "For fully automated container builds, you can create a reusable auth key:"
echo ""
echo "1. 🌐 Open: https://login.tailscale.com/admin/settings/keys"
echo "2. ✅ Click 'Generate auth key'"
echo "3. ✅ Check 'Reusable' (recommended for development)"
echo "4. ✅ Set expiration (90 days recommended)"
echo "5. 📋 Copy the generated key"
echo ""
echo "6. 🔧 Add to your shell profile:"
echo "   echo 'export TS_AUTHKEY=\"tskey-auth-xxxxxxxxxxxxxx\"' >> ~/.bashrc"
echo "   # or ~/.zshrc depending on your shell"
echo ""
echo "7. 🔄 Reload shell: source ~/.bashrc"
echo ""
echo "After setup, container builds will automatically authenticate!"
echo ""
echo "💡 Alternative: Set TS_AUTHKEY as environment variable in VS Code settings"
echo "   or in your devcontainer.json containerEnv section"