#!/usr/bin/env python3
"""Download wiki calculator gadgets into shared JS/CSS for offline/WebView use."""

from __future__ import annotations

import re
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[2]
SHARED_JS = ROOT / "shared" / "js" / "mediawiki"
SHARED_CSS = ROOT / "shared" / "css"
ORIGIN = "https://oldschool.runescape.wiki"

JS_URL = f"{ORIGIN}/w/MediaWiki:Gadget-calc-core.js?action=raw"
CSS_URL = f"{ORIGIN}/w/MediaWiki:Gadget-calc.css?action=raw"


def fetch(url: str) -> str:
    request = Request(url, headers={"User-Agent": "osrswiki-calc-core-extractor/1.0"})
    with urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8")


def patch_core(body: str) -> str:
    # Prefer GET so WebView interceptors that cannot read POST bodies still work.
    # Remaining oversized requests are handled by the native calculator API bridge.
    patched = re.sub(
        r"if\s*\(\s*code\.length\s*>\s*1900\s*\)\s*\{\s*method\s*=\s*'POST';\s*\}",
        "if (code.length > 7000) {\n method = 'POST';\n }",
        body,
        count=1,
    )
    patched = patched.replace("url:'/api.php'", "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    patched = patched.replace('url:"/api.php"', "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    patched = patched.replace("url: '/api.php'", "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    # Wiki skins expose #bodyContent. App WebViews often only have .mw-body-content.
    patched = patched.replace(
        "$('#bodyContent')",
        "$(document.getElementById('bodyContent') || document.body)",
    )
    patched = patched.replace(
        "initClasses: function () {\n            var hasOwn = Object.prototype.hasOwnProperty;",
        "initClasses: function () {\n"
        "            if (!mw.widgets || !mw.widgets.TitleInputWidget) {\n"
        "                return;\n"
        "            }\n"
        "            var hasOwn = Object.prototype.hasOwnProperty;",
    )
    return patched


WRAPPER_PREFIX = """/**
 * Bundled from MediaWiki:Gadget-calc-core.js (CC BY-NC-SA 3.0).
 * Regenerated by tools/js/extract-gadget-calc-core.py.
 */
(function () {
    window.__osrsCalcErrors = window.__osrsCalcErrors || [];
    window.addEventListener('error', function (ev) {
        window.__osrsCalcErrors.push(String((ev && ev.message) || ev));
    });
    function osrsMakeModuleRequire(files) {
        var cache = {};
        return function osrsRequire(name) {
            var key = String(name || '').replace(/^\.\//, '');
            if (Object.prototype.hasOwnProperty.call(cache, key)) {
                return cache[key];
            }
            if (files && files[key]) {
                var file = files[key];
                var moduleObj = { exports: {} };
                if (typeof file === 'function') {
                    file(osrsRequire, moduleObj, moduleObj.exports);
                    cache[key] = moduleObj.exports;
                    return cache[key];
                }
                cache[key] = file;
                return file;
            }
            try {
                return mw.loader.require(name);
            } catch (ignore) {
                if (key === 'jquery' || key === 'jquery.js') {
                    return window.jQuery || window.$;
                }
                if (key === 'oojs' || key.indexOf('oojs') === 0) {
                    return window.OO;
                }
                return undefined;
            }
        };
    }
    function osrsRunModuleScript(script) {
        osrsEnsureJQueryAlias();
        var $ = window.jQuery || window.$;
        if (typeof script === 'function') {
            try {
                script($, $, osrsMakeModuleRequire(null), { exports: {} });
                return true;
            } catch (first) {
                try {
                    script($, window.OO);
                    return true;
                } catch (second) {
                    try {
                        script();
                        return true;
                    } catch (third) {
                        window.__osrsCalcErrors.push('runModule: ' + String((third && third.message) || third));
                        return false;
                    }
                }
            }
        }
        if (script && typeof script === 'object' && script.files && script.main) {
            var req = osrsMakeModuleRequire(script.files);
            var main = script.files[script.main];
            if (typeof main === 'function') {
                try {
                    var moduleObj = { exports: {} };
                    main(req, moduleObj, moduleObj.exports);
                    return true;
                } catch (packaged) {
                    window.__osrsCalcErrors.push('runModule: ' + String((packaged && packaged.message) || packaged));
                }
            }
        }
        return false;
    }
    window.__osrsPendingOOUIScripts = window.__osrsPendingOOUIScripts || [];
    function osrsEnsureJQueryAlias() {
        if (window.jQuery && !window.$) {
            window.$ = window.jQuery;
        }
        if (window.$ && !window.jQuery) {
            window.jQuery = window.$;
        }
        return !!(window.$ && window.jQuery);
    }
    function osrsJqueryReady() {
        osrsEnsureJQueryAlias();
        var jq = window.jQuery || window.$;
        return !!(jq && typeof jq === 'function' && typeof jq.proxy === 'function' && jq.fn);
    }
    function osrsInstallPriority(name) {
        var key = String(name || '').split('@')[0].trim();
        if (key === 'jquery') {
            return 0;
        }
        if (key === 'oojs') {
            return 1;
        }
        if (key.indexOf('oojs-ui-core') === 0) {
            return 2;
        }
        if (key.indexOf('oojs-ui-widgets') === 0) {
            return 3;
        }
        if (key.indexOf('mediawiki.widgets') === 0) {
            return 4;
        }
        return 5;
    }
    function osrsCanInstallModule(name) {
        var key = String(name || '').split('@')[0].trim();
        if (key === 'jquery') {
            return true;
        }
        if (key === 'oojs') {
            return true;
        }
        if (key.indexOf('oojs-ui-core') === 0) {
            return osrsJqueryReady() && !!window.OO;
        }
        if (key.indexOf('oojs-ui-widgets') === 0) {
            return !!(window.OO && OO.ui && typeof OO.ui.HorizontalLayout === 'function');
        }
        if (key.indexOf('mediawiki.widgets') === 0) {
            return !!(window.OO && OO.ui && typeof OO.ui.ButtonOptionWidget === 'function');
        }
        return osrsJqueryReady();
    }
    function osrsQueuePending(name, script) {
        if (window.__osrsPendingOOUIScripts.length >= 16) {
            return;
        }
        window.__osrsPendingOOUIScripts.push([name, script]);
        window.__osrsPendingOOUIScripts.sort(function (a, b) {
            return osrsInstallPriority(a[0]) - osrsInstallPriority(b[0]);
        });
    }
    function osrsInstallImplementedScript(name, script) {
        if (osrsCalcCoreDepsReady()) {
            return true;
        }
        var key = String(name || '').split('@')[0].trim();
        if (!/oojs|mediawiki\.widgets|^jquery$/i.test(key)) {
            return false;
        }
        if (!osrsCanInstallModule(key)) {
            osrsQueuePending(name, script);
            return false;
        }
        var ok = osrsRunModuleScript(script);
        if (!ok) {
            osrsQueuePending(name, script);
            return false;
        }
        try {
            var ready = {};
            ready[key] = 'ready';
            if (window.mw && mw.loader && typeof mw.loader.state === 'function') {
                mw.loader.state(ready);
            }
        } catch (ignore) {}
        return true;
    }
    function osrsFlushPendingOOUI() {
        osrsEnsureJQueryAlias();
        var pending = window.__osrsPendingOOUIScripts || [];
        if (!pending.length) {
            return;
        }
        window.__osrsPendingOOUIScripts = [];
        pending.forEach(function (item) {
            osrsInstallImplementedScript(item[0], item[1]);
        });
    }
    function osrsPatchLoaderMethod(methodName) {
        if (!window.mw || !mw.loader || typeof mw.loader[methodName] !== 'function') {
            return false;
        }
        if (mw.loader[methodName].__osrsPatched) {
            return true;
        }
        var orig = mw.loader[methodName];
        mw.loader[methodName] = function () {
            var args = arguments;
            var threw = null;
            var result;
            try {
                result = orig.apply(this, args);
            } catch (err) {
                threw = err;
                var msg = String((err && err.message) || err);
                if (msg.indexOf('already implemented') === -1 && msg.indexOf('NotFoundError') === -1) {
                    window.__osrsCalcErrors.push(msg);
                    throw err;
                }
            }
            if (!osrsCalcCoreDepsReady()) {
                try {
                    var payload = null;
                    var name = '';
                    if (methodName === 'impl' && typeof args[0] === 'function') {
                        payload = args[0]();
                        name = payload && payload[0];
                        osrsInstallImplementedScript(name, payload && payload[1]);
                    } else if (methodName === 'implement') {
                        name = args[0];
                        osrsInstallImplementedScript(name, args[1]);
                    }
                } catch (ignore) {}
            }
            return result;
        };
        mw.loader[methodName].__osrsPatched = true;
        return true;
    }
    function osrsPatchLoaderImpl() {
        if (!window.mw || !mw.loader) {
            setTimeout(osrsPatchLoaderImpl, 10);
            return;
        }
        var implReady = osrsPatchLoaderMethod('impl');
        var implementReady = osrsPatchLoaderMethod('implement');
        if (!implReady && !implementReady) {
            setTimeout(osrsPatchLoaderImpl, 10);
        }
    }
    osrsPatchLoaderImpl();
    function osrsEnsureMwHelpers() {
        if (!window.mw) {
            return;
        }
        mw.html = mw.html || {};
        if (typeof mw.html.escape !== 'function') {
            mw.html.escape = function (value) {
                return String(value == null ? '' : value)
                    .replace(/&/g, '&amp;')
                    .replace(/</g, '&lt;')
                    .replace(/>/g, '&gt;')
                    .replace(/"/g, '&quot;');
            };
        }
        if (typeof mw.hook !== 'function') {
            mw.hook = function () {
                return {
                    add: function () { return this; },
                    fire: function () { return this; },
                    remove: function () { return this; }
                };
            };
        }
        if (typeof mw.log !== 'function') {
            mw.log = function () {};
        }
        mw.log.warn = mw.log.warn || function () {};
        mw.language = mw.language || {};
        if (typeof mw.language.getFallbackLanguageChain !== 'function') {
            mw.language.getFallbackLanguageChain = function () { return ['en']; };
        }
    }
    function osrsEnsureRs() {
        window.rs = window.rs || window.rswiki || {};
        if (typeof window.rs.hasLocalStorage !== 'function') {
            window.rs.hasLocalStorage = function () {
                try { return !!window.localStorage; } catch (err) { return false; }
            };
        }
    }
    function osrsEnsureOOUITheme() {
        if (!window.OO || !OO.ui) {
            return;
        }
        if (OO.ui.theme) {
            return;
        }
        try {
            if (typeof OO.ui.WikimediaUITheme === 'function') {
                OO.ui.theme = new OO.ui.WikimediaUITheme();
            } else if (typeof OO.ui.Theme === 'function') {
                OO.ui.theme = new OO.ui.Theme();
            }
        } catch (err) {
            window.__osrsCalcErrors = window.__osrsCalcErrors || [];
            window.__osrsCalcErrors.push(String(err && err.message || err));
        }
        if (!OO.ui.theme) {
            OO.ui.theme = {
                getElementClasses: function () { return { on: [], off: [] }; },
                queueUpdateElementClasses: function () {},
                updateElementClasses: function () {},
                getDialogTransitionDuration: function () { return 0; }
            };
        }
    }
    function osrsCalcCoreDepsReady() {
        var $ = window.jQuery || window.$;
        var cfg = '';
        try {
            var pre = document.querySelector('pre.jcConfig');
            cfg = pre && pre.textContent ? String(pre.textContent) : '';
        } catch (ignore) {}
        var base = !!( $ && window.OO && OO.ui &&
            typeof OO.ui.FieldsetLayout === 'function' &&
            typeof OO.ui.ButtonInputWidget === 'function' &&
            typeof OO.ui.ButtonOptionWidget === 'function' &&
            typeof OO.ui.DropdownInputWidget === 'function' &&
            typeof OO.ui.CheckboxInputWidget === 'function');
        if (!base) {
            return false;
        }
        if (/toggleswitch/i.test(cfg) && typeof OO.ui.ToggleSwitchWidget !== 'function') {
            return false;
        }
        if (/\|\s*group\s*\|/i.test(cfg) && typeof OO.ui.HorizontalLayout !== 'function') {
            return false;
        }
        if (/\|\s*hs\s*\|/i.test(cfg) && typeof OO.ui.ActionFieldLayout !== 'function') {
            return false;
        }
        return true;
    }
    function osrsMarkCalcCoreRegistered() {
        if (!window.mw || !mw.loader) {
            return;
        }
        if (window.__osrsCalcCoreImplemented) {
            return;
        }
        window.__osrsCalcCoreImplemented = true;
        try {
            if (typeof mw.loader.implement === 'function') {
                mw.loader.implement('ext.gadget.calc-core', function () {});
            }
        } catch (err) {}
        try {
            if (typeof mw.loader.state === 'function') {
                mw.loader.state({ 'ext.gadget.calc-core': 'ready' });
            }
        } catch (err2) {}
    }
    function osrsUnblockOOUI() {
        if (!window.mw || !mw.loader || typeof mw.loader.state !== 'function') {
            return;
        }
        if (osrsCalcCoreDepsReady()) {
            return;
        }
        var stuck = {};
        [
            'mediawiki.page.ready',
            'mediawiki.user',
            'oojs-ui-core.icons',
            'oojs-ui-core.styles',
            'oojs-ui.styles.indicators',
            'oojs-ui-widgets.icons',
            'oojs-ui-windows.icons',
            'oojs-ui-windows.styles',
            'mediawiki.widgets.styles',
            'oojs-ui.styles.icons-content',
            'oojs-ui.styles.icons-editing-advanced'
        ].forEach(function (name) {
            var state = mw.loader.getState && mw.loader.getState(name);
            if (state && state !== 'ready') {
                stuck[name] = 'ready';
            }
        });
        if (Object.keys(stuck).length) {
            try { mw.loader.state(stuck); } catch (err3) {}
        }
    }
    function osrsRunCalcCoreFactory() {
        osrsEnsureJQueryAlias();
        osrsFlushPendingOOUI();
        osrsEnsureMwHelpers();
        osrsMarkCalcCoreRegistered();
        osrsUnblockOOUI();
        var $ = window.jQuery || window.$;
        if (!osrsCalcCoreDepsReady()) {
            setTimeout(osrsRunCalcCoreFactory, 25);
            return;
        }
        osrsEnsureRs();
        osrsEnsureOOUITheme();
        if (!OO.ui.theme) {
            window.__osrsCalcThemeWait = (window.__osrsCalcThemeWait || 0) + 1;
            if (window.__osrsCalcThemeWait < 20) {
                setTimeout(osrsRunCalcCoreFactory, 25);
                return;
            }
            osrsEnsureOOUITheme();
        }
        // Wait briefly for the app runtime to patch jQuery.ajax so parse/hiscores
        // requests hit the native wiki proxy instead of a CORS-blocked origin.
        if (!(window.jQuery && jQuery.ajax && jQuery.ajax.__osrsCalculatorPatched)) {
            window.__osrsCalcAjaxWait = (window.__osrsCalcAjaxWait || 0) + 1;
            if (window.__osrsCalcAjaxWait < 80) {
                setTimeout(osrsRunCalcCoreFactory, 25);
                return;
            }
        }
        if (window.__osrsCalcCoreFactoryRan) {
            return;
        }
        window.__osrsCalcCoreFactoryRan = true;
        document.documentElement.setAttribute('data-osrs-calc-core', 'running');
        try {
        (function ($, jQuery) {
"""

WRAPPER_SUFFIX = """
            document.documentElement.setAttribute('data-osrs-calc-core', 'ready');
        })($, $);
        } catch (err) {
            window.__osrsCalcCoreFactoryRan = false;
            window.__osrsCalcErrors = window.__osrsCalcErrors || [];
            window.__osrsCalcErrors.push(String(err && err.message || err));
            setTimeout(osrsRunCalcCoreFactory, 50);
        }
    }
    window.__osrsKickCalcCore = osrsRunCalcCoreFactory;
    function osrsBootCalcCore() {
        if (!window.mw || !mw.loader) {
            setTimeout(osrsBootCalcCore, 25);
            return;
        }
        osrsMarkCalcCoreRegistered();
        if (window.mw && mw.loader && typeof mw.loader.state === 'function' && !osrsCalcCoreDepsReady()) {
            var stuck = {};
            ['mediawiki.page.ready', 'mediawiki.user'].forEach(function (name) {
                var state = mw.loader.getState && mw.loader.getState(name);
                if (state && state !== 'ready' && state !== 'error') {
                    stuck[name] = 'ready';
                }
            });
            if (Object.keys(stuck).length) {
                try { mw.loader.state(stuck); } catch (err3) {}
            }
        }
        osrsRunCalcCoreFactory();
    }
    osrsBootCalcCore();
}());
"""


def wrap_js(body: str) -> str:
    patched = patch_core(body)
    return WRAPPER_PREFIX + patched.rstrip() + WRAPPER_SUFFIX


def wrap_css(body: str) -> str:
    return (
        "/* Bundled from MediaWiki:Gadget-calc.css (CC BY-NC-SA 3.0).\n"
        " * Regenerated by tools/js/extract-gadget-calc-core.py.\n"
        " */\n"
        f"{body.rstrip()}\n"
    )


def main() -> None:
    SHARED_JS.mkdir(parents=True, exist_ok=True)
    SHARED_CSS.mkdir(parents=True, exist_ok=True)
    js_dest = SHARED_JS / "gadget_calc_core.js"
    css_dest = SHARED_CSS / "gadget_calc.css"
    print(f"Fetching calc-core from {JS_URL}")
    js_dest.write_text(wrap_js(fetch(JS_URL)), encoding="utf-8")
    print(f"Wrote {js_dest} ({js_dest.stat().st_size} bytes)")
    print(f"Fetching calc CSS from {CSS_URL}")
    css_dest.write_text(wrap_css(fetch(CSS_URL)), encoding="utf-8")
    print(f"Wrote {css_dest} ({css_dest.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
