#!/usr/bin/env python3
"""Download wiki calculator gadgets into shared JS/CSS for offline/WebView use."""

from __future__ import annotations

import re
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[2]
SHARED_JS = ROOT / "shared" / "js" / "mediawiki"
SHARED_CSS = ROOT / "shared" / "css"
ORIGIN = "https://oldschool.runescape.wiki"

JS_URL = f"{ORIGIN}/w/MediaWiki:Gadget-calc-core.js?action=raw"
CSS_URL = f"{ORIGIN}/w/MediaWiki:Gadget-calc.css?action=raw"


def fetch(url: str) -> str:
    request = Request(url, headers={"User-Agent": "osrswiki-calc-core-extractor/1.0"})
    with urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8")


def patch_core(body: str) -> str:
    # Prefer GET so WebView interceptors that cannot read POST bodies still work.
    # Remaining oversized requests are handled by the native calculator API bridge.
    patched = re.sub(
        r"if\s*\(\s*code\.length\s*>\s*1900\s*\)\s*\{\s*method\s*=\s*'POST';\s*\}",
        "if (code.length > 7000) {\n method = 'POST';\n }",
        body,
        count=1,
    )
    patched = patched.replace("url:'/api.php'", "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    patched = patched.replace('url:"/api.php"', "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    patched = patched.replace("url: '/api.php'", "url: (window.osrsWikiCalculatorApiUrl || '/api.php')")
    # Wiki skins expose #bodyContent. App WebViews often only have .mw-body-content.
    patched = patched.replace(
        "$('#bodyContent')",
        "$(document.getElementById('bodyContent') || document.body)",
    )
    patched = patched.replace(
        "initClasses: function () {\n            var hasOwn = Object.prototype.hasOwnProperty;",
        "initClasses: function () {\n"
        "            if (!mw.widgets || !mw.widgets.TitleInputWidget) {\n"
        "                return;\n"
        "            }\n"
        "            var hasOwn = Object.prototype.hasOwnProperty;",
    )
    return patched


WRAPPER_PREFIX = """/**
 * Bundled from MediaWiki:Gadget-calc-core.js (CC BY-NC-SA 3.0).
 * Regenerated by tools/js/extract-gadget-calc-core.py.
 */
(function () {
    window.__osrsCalcErrors = window.__osrsCalcErrors || [];
    window.addEventListener('error', function (ev) {
        window.__osrsCalcErrors.push(String((ev && ev.message) || ev));
    });
    function osrsPatchLoaderImpl() {
        if (!window.mw || !mw.loader || typeof mw.loader.impl !== 'function') {
            setTimeout(osrsPatchLoaderImpl, 10);
            return;
        }
        if (mw.loader.impl.__osrsPatched) {
            return;
        }
        var orig = mw.loader.impl;
        mw.loader.impl = function (declarator) {
            try {
                return orig.apply(this, arguments);
            } catch (err) {
                var msg = String((err && err.message) || err);
                window.__osrsCalcErrors.push(msg);
                if (msg.indexOf('already implemented') === -1 && msg.indexOf('NotFoundError') === -1) {
                    throw err;
                }
            }
        };
        mw.loader.impl.__osrsPatched = true;
    }
    osrsPatchLoaderImpl();
    function osrsEnsureRs() {
        window.rs = window.rs || window.rswiki || {};
        if (typeof window.rs.hasLocalStorage !== 'function') {
            window.rs.hasLocalStorage = function () {
                try { return !!window.localStorage; } catch (err) { return false; }
            };
        }
    }
    function osrsEnsureOOUITheme() {
        if (!window.OO || !OO.ui) {
            return;
        }
        if (OO.ui.theme) {
            return;
        }
        try {
            if (typeof OO.ui.WikimediaUITheme === 'function') {
                OO.ui.theme = new OO.ui.WikimediaUITheme();
            } else if (typeof OO.ui.Theme === 'function') {
                OO.ui.theme = new OO.ui.Theme();
            }
        } catch (err) {
            window.__osrsCalcErrors = window.__osrsCalcErrors || [];
            window.__osrsCalcErrors.push(String(err && err.message || err));
        }
    }
    function osrsCalcCoreDepsReady() {
        var $ = window.jQuery || window.$;
        return !!( $ && window.OO && OO.ui &&
            typeof OO.ui.FieldsetLayout === 'function' &&
            typeof OO.ui.ButtonInputWidget === 'function');
    }
    function osrsMarkCalcCoreRegistered() {
        if (!window.mw || !mw.loader) {
            return;
        }
        if (window.__osrsCalcCoreImplemented) {
            return;
        }
        window.__osrsCalcCoreImplemented = true;
        try {
            if (typeof mw.loader.implement === 'function') {
                mw.loader.implement('ext.gadget.calc-core', function () {});
            }
        } catch (err) {}
        try {
            if (typeof mw.loader.state === 'function') {
                mw.loader.state({ 'ext.gadget.calc-core': 'ready' });
            }
        } catch (err2) {}
    }
    function osrsUnblockOOUI() {
        if (!window.mw || !mw.loader || typeof mw.loader.state !== 'function') {
            return;
        }
        if (osrsCalcCoreDepsReady()) {
            return;
        }
        var stuck = {};
        [
            'mediawiki.page.ready',
            'mediawiki.user',
            'oojs-ui-core.icons',
            'oojs-ui-core.styles',
            'oojs-ui.styles.indicators',
            'oojs-ui-widgets.icons',
            'mediawiki.widgets.styles',
            'oojs-ui.styles.icons-content',
            'oojs-ui.styles.icons-editing-advanced'
        ].forEach(function (name) {
            var state = mw.loader.getState && mw.loader.getState(name);
            if (state === 'loaded' || state === 'loading') {
                stuck[name] = 'ready';
            }
        });
        if (Object.keys(stuck).length) {
            try { mw.loader.state(stuck); } catch (err3) {}
        }
    }
    function osrsRunCalcCoreFactory() {
        osrsMarkCalcCoreRegistered();
        osrsUnblockOOUI();
        var $ = window.jQuery || window.$;
        if (!osrsCalcCoreDepsReady()) {
            setTimeout(osrsRunCalcCoreFactory, 25);
            return;
        }
        osrsEnsureRs();
        osrsEnsureOOUITheme();
        if (!OO.ui.theme) {
            setTimeout(osrsRunCalcCoreFactory, 25);
            return;
        }
        if (!(window.jQuery && jQuery.ajax && jQuery.ajax.__osrsCalculatorPatched)) {
            window.__osrsCalcAjaxWait = (window.__osrsCalcAjaxWait || 0) + 1;
            if (window.__osrsCalcAjaxWait < 80) {
                setTimeout(osrsRunCalcCoreFactory, 25);
                return;
            }
        }
        if (window.__osrsCalcCoreFactoryRan) {
            return;
        }
        window.__osrsCalcCoreFactoryRan = true;
        document.documentElement.setAttribute('data-osrs-calc-core', 'running');
        try {
        (function ($, jQuery) {
"""

WRAPPER_SUFFIX = """
            document.documentElement.setAttribute('data-osrs-calc-core', 'ready');
        })($, $);
        } catch (err) {
            window.__osrsCalcCoreFactoryRan = false;
            window.__osrsCalcErrors = window.__osrsCalcErrors || [];
            window.__osrsCalcErrors.push(String(err && err.message || err));
            setTimeout(osrsRunCalcCoreFactory, 50);
        }
    }
    window.__osrsKickCalcCore = osrsRunCalcCoreFactory;
    function osrsBootCalcCore() {
        if (!window.mw || !mw.loader) {
            setTimeout(osrsBootCalcCore, 25);
            return;
        }
        osrsMarkCalcCoreRegistered();
        if (window.mw && mw.loader && typeof mw.loader.state === 'function' && !osrsCalcCoreDepsReady()) {
            var stuck = {};
            ['mediawiki.page.ready', 'mediawiki.user'].forEach(function (name) {
                var state = mw.loader.getState && mw.loader.getState(name);
                if (state && state !== 'ready' && state !== 'error') {
                    stuck[name] = 'ready';
                }
            });
            if (Object.keys(stuck).length) {
                try { mw.loader.state(stuck); } catch (err3) {}
            }
        }
        osrsRunCalcCoreFactory();
    }
    osrsBootCalcCore();
}());
"""


def wrap_js(body: str) -> str:
    patched = patch_core(body)
    return WRAPPER_PREFIX + patched.rstrip() + WRAPPER_SUFFIX


def wrap_css(body: str) -> str:
    return (
        "/* Bundled from MediaWiki:Gadget-calc.css (CC BY-NC-SA 3.0).\n"
        " * Regenerated by tools/js/extract-gadget-calc-core.py.\n"
        " */\n"
        f"{body.rstrip()}\n"
    )


def main() -> None:
    SHARED_JS.mkdir(parents=True, exist_ok=True)
    SHARED_CSS.mkdir(parents=True, exist_ok=True)
    js_dest = SHARED_JS / "gadget_calc_core.js"
    css_dest = SHARED_CSS / "gadget_calc.css"
    print(f"Fetching calc-core from {JS_URL}")
    js_dest.write_text(wrap_js(fetch(JS_URL)), encoding="utf-8")
    print(f"Wrote {js_dest} ({js_dest.stat().st_size} bytes)")
    print(f"Fetching calc CSS from {CSS_URL}")
    css_dest.write_text(wrap_css(fetch(CSS_URL)), encoding="utf-8")
    print(f"Wrote {css_dest} ({css_dest.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
