#!/usr/bin/env python3

import argparse
import json
import math
from pathlib import Path


def load_json(path):
    return json.loads(Path(path).read_text())


def float_value(value):
    return float(value)


def text_number(value):
    if isinstance(value, str):
        return value
    return str(float(value))


def first_present(*values):
    for value in values:
        if value is not None:
            return value
    return None


def metadata_projection(manifest, metadata):
    projection = manifest.get("projection", {})
    game_bounds = metadata.get("gameBounds", {}) if metadata else {}
    source_image = metadata.get("sourceImage", {}) if metadata else {}
    tile_pyramid = metadata.get("tilePyramid", {}) if metadata else {}

    scale = float_value(first_present(metadata.get("gameCoordScale") if metadata else None, projection.get("gameCoordScale"), 4.0))
    min_x = float_value(first_present(game_bounds.get("minX"), projection.get("gameMinX")))
    max_y = float_value(first_present(game_bounds.get("maxY"), projection.get("gameMaxY")))

    source_width = first_present(source_image.get("width"), projection.get("sourceImageWidth"))
    source_height = first_present(source_image.get("height"), projection.get("sourceImageHeight"))
    max_x = first_present(game_bounds.get("maxX"), projection.get("gameMaxX"))
    min_y = first_present(game_bounds.get("minY"), projection.get("gameMinY"))

    if max_x is None:
        if source_width is None:
            raise SystemExit("Map metadata must provide gameBounds.maxX or sourceImage.width")
        max_x = min_x + float_value(source_width) / scale
    if min_y is None:
        if source_height is None:
            raise SystemExit("Map metadata must provide gameBounds.minY or sourceImage.height")
        min_y = max_y - float_value(source_height) / scale

    tile_size = float_value(first_present(tile_pyramid.get("tileSize"), projection.get("tileSize"), 1024.0))
    max_zoom = int(first_present(tile_pyramid.get("maxZoom"), projection.get("maxZoom"), 6))
    canvas_size = float_value(first_present(tile_pyramid.get("canvasSize"), projection.get("canvasSize"), (2**max_zoom) * tile_size))

    if source_width is None:
        source_width = (float_value(max_x) - min_x) * scale
    if source_height is None:
        source_height = (max_y - float_value(min_y)) * scale

    return {
        "scale": scale,
        "min_x": min_x,
        "max_x": float_value(max_x),
        "min_y": float_value(min_y),
        "max_y": max_y,
        "source_width": float_value(source_width),
        "source_height": float_value(source_height),
        "tile_size": tile_size,
        "max_zoom": max_zoom,
        "canvas_size": canvas_size,
    }


def map_coordinate(game_x, game_y, projection):
    px = (game_x - projection["min_x"]) * projection["scale"]
    py = (projection["max_y"] - game_y) * projection["scale"]
    nx = px / projection["canvas_size"]
    ny = py / projection["canvas_size"]
    lon = -180.0 + nx * 360.0
    lat = math.degrees(math.atan(math.sinh(math.pi * (1.0 - 2.0 * ny))))
    return lat, lon


def validate_target(game_x, game_y, projection):
    if not projection["min_x"] <= game_x <= projection["max_x"]:
        raise SystemExit(
            f"Default map game x {game_x} is outside generated bounds "
            f"{projection['min_x']}..{projection['max_x']}"
        )
    if not projection["min_y"] <= game_y <= projection["max_y"]:
        raise SystemExit(
            f"Default map game y {game_y} is outside generated bounds "
            f"{projection['min_y']}..{projection['max_y']}"
        )

    px = (game_x - projection["min_x"]) * projection["scale"]
    py = (projection["max_y"] - game_y) * projection["scale"]
    if not 0.0 <= px <= projection["source_width"]:
        raise SystemExit(f"Default map pixel x {px} is outside source image width {projection['source_width']}")
    if not 0.0 <= py <= projection["source_height"]:
        raise SystemExit(f"Default map pixel y {py} is outside source image height {projection['source_height']}")


def write_swift(path, game_x, game_y, plane, projection, latitude_text, longitude_text, zoom_text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""//
//  osrsMapDefaultView.swift
//  OSRS Wiki
//
//  Generated by scripts/shared/stamp-map-default-view.py from shared/map-default-view.json.
//

import CoreLocation

enum osrsMapDefaultView {{
    static let gameX = {game_x:.1f}
    static let gameY = {game_y:.1f}
    static let plane = {plane}
    static let gameCoordScale = {projection['scale']:.1f}
    static let gameMinX = {projection['min_x']:.1f}
    static let gameMaxX = {projection['max_x']:.1f}
    static let gameMinY = {projection['min_y']:.1f}
    static let gameMaxY = {projection['max_y']:.1f}
    static let sourceImageWidth = {projection['source_width']:.1f}
    static let sourceImageHeight = {projection['source_height']:.1f}
    static let tileSize = {projection['tile_size']:.1f}
    static let maxZoom = {projection['max_zoom']}
    static let canvasSize = {projection['canvas_size']:.1f}
    static let latitude = {latitude_text}
    static let longitude = {longitude_text}
    static let zoom = {zoom_text}

    static let coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    static var southWestCoordinate: CLLocationCoordinate2D {{ mapCoordinate(gameX: gameMinX, gameY: gameMinY) }}
    static var northEastCoordinate: CLLocationCoordinate2D {{ mapCoordinate(gameX: gameMaxX, gameY: gameMaxY) }}

    static func mapCoordinate(gameX: Double, gameY: Double) -> CLLocationCoordinate2D {{
        CLLocationCoordinate2D(latitude: latitudeForGameY(gameY), longitude: longitudeForGameX(gameX))
    }}

    static func longitudeForGameX(_ gameX: Double) -> Double {{
        let px = (gameX - gameMinX) * gameCoordScale
        let nx = px / canvasSize
        return -180.0 + nx * 360.0
    }}

    static func latitudeForGameY(_ gameY: Double) -> Double {{
        let py = (gameMaxY - gameY) * gameCoordScale
        let ny = py / canvasSize
        return atan(sinh(.pi * (1.0 - 2.0 * ny))) * 180.0 / .pi
    }}
}}
""",
        encoding="utf-8",
    )


def write_kotlin(path, game_x, game_y, plane, projection, latitude_text, longitude_text, zoom_text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""package com.omiyawaki.osrswiki.ui.map

/**
 * Generated by scripts/shared/stamp-map-default-view.py from shared/map-default-view.json.
 */
object osrsMapDefaultView {{
    const val GAME_X = {game_x:.1f}
    const val GAME_Y = {game_y:.1f}
    const val PLANE = {plane}
    const val GAME_COORD_SCALE = {projection['scale']:.1f}
    const val GAME_MIN_X = {projection['min_x']:.1f}
    const val GAME_MAX_X = {projection['max_x']:.1f}
    const val GAME_MIN_Y = {projection['min_y']:.1f}
    const val GAME_MAX_Y = {projection['max_y']:.1f}
    const val SOURCE_IMAGE_WIDTH = {projection['source_width']:.1f}
    const val SOURCE_IMAGE_HEIGHT = {projection['source_height']:.1f}
    const val TILE_SIZE = {projection['tile_size']:.1f}
    const val MAX_ZOOM = {projection['max_zoom']}
    const val CANVAS_SIZE = {projection['canvas_size']:.1f}
    const val LATITUDE = {latitude_text}
    const val LONGITUDE = {longitude_text}
    const val ZOOM = {zoom_text}

    fun longitudeForGameX(gameX: Double): Double {{
        val px = (gameX - GAME_MIN_X) * GAME_COORD_SCALE
        val nx = px / CANVAS_SIZE
        return -180.0 + nx * 360.0
    }}

    fun latitudeForGameY(gameY: Double): Double {{
        val py = (GAME_MAX_Y - gameY) * GAME_COORD_SCALE
        val ny = py / CANVAS_SIZE
        return Math.toDegrees(Math.atan(Math.sinh(Math.PI * (1.0 - 2.0 * ny))))
    }}
}}
""",
        encoding="utf-8",
    )


def main():
    parser = argparse.ArgumentParser(description="Stamp generated iOS and Android default map view sources.")
    parser.add_argument("--repo-root", default=".", help="Repository root whose platform files should be generated")
    parser.add_argument("--manifest", help="Path to shared/map-default-view.json")
    parser.add_argument("--metadata", help="Path to generated map-metadata.json")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    manifest_path = Path(args.manifest).resolve() if args.manifest else repo_root / "shared" / "map-default-view.json"
    metadata_path = Path(args.metadata).resolve() if args.metadata else None

    manifest = load_json(manifest_path)
    metadata = load_json(metadata_path) if metadata_path and metadata_path.exists() else {}

    game = manifest["gameCoordinates"]
    game_x = float_value(game["x"])
    game_y = float_value(game["y"])
    plane = int(game["plane"])
    projection = metadata_projection(manifest, metadata)

    validate_target(game_x, game_y, projection)

    computed_lat, computed_lon = map_coordinate(game_x, game_y, projection)
    maplibre = manifest.get("mapLibre", {})
    latitude_text = text_number(maplibre.get("latitude", computed_lat))
    longitude_text = text_number(maplibre.get("longitude", computed_lon))
    zoom_text = text_number(maplibre.get("zoom", "7.3414426741929"))

    latitude = float_value(latitude_text)
    longitude = float_value(longitude_text)
    if abs(computed_lat - latitude) > 1e-12 or abs(computed_lon - longitude) > 1e-12:
        raise SystemExit(
            "shared/map-default-view.json mapLibre coordinates do not match generated metadata: "
            f"computed=({computed_lat}, {computed_lon}) manifest=({latitude}, {longitude})"
        )

    swift_path = repo_root / "platforms/ios/osrswiki/Models/osrsMapDefaultView.swift"
    kotlin_path = repo_root / "platforms/android/app/src/main/java/com/omiyawaki/osrswiki/ui/map/osrsMapDefaultView.kt"
    write_swift(swift_path, game_x, game_y, plane, projection, latitude_text, longitude_text, zoom_text)
    write_kotlin(kotlin_path, game_x, game_y, plane, projection, latitude_text, longitude_text, zoom_text)

    print(f"  - {swift_path.relative_to(repo_root)}")
    print(f"  - {kotlin_path.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
