#!/usr/bin/env bash
# Build shared/css/critical-article.min.css from the 10 critical article sheets
# in PageHtmlBuilder / osrsPageHtmlBuilder order. Source of truth remains the
# individual files; regenerate after CSS edits.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
python3 - <<'PY'
from pathlib import Path
import re, json, hashlib, sys

root = Path(".").resolve()
sources = [
    ("styles/themes.css", root / "shared/css/themes.css"),
    ("styles/base.css", root / "shared/css/base.css"),
    ("styles/fonts.css", root / "shared/css/fonts.css"),
    ("styles/layout.css", root / "shared/css/layout.css"),
    ("styles/components.css", root / "shared/css/components.css"),
    # Platform web sheets: Android assets are the checked-in generator input.
    # Keep iOS Assets/web/collapsible_*.css in sync separately when they diverge.
    ("web/collapsible_tables.css", root / "platforms/android/app/src/main/assets/web/collapsible_tables.css"),
    ("web/collapsible_sections.css", root / "platforms/android/app/src/main/assets/web/collapsible_sections.css"),
    ("web/switch_infobox_styles.css", root / "shared/js/switch_infobox_styles.css"),
    ("styles/fixes.css", root / "shared/css/fixes.css"),
    ("styles/gadget_calc.css", root / "shared/css/gadget_calc.css"),
]

def minify(css: str) -> str:
    out = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out = re.sub(r"\s+", " ", out)
    return out.strip()

parts = []
raw_bytes = 0
for logical, path in sources:
    if not path.exists():
        print(f"ERROR: missing source {path}", file=sys.stderr)
        sys.exit(1)
    text = path.read_text(encoding="utf-8")
    raw_bytes += len(text.encode("utf-8"))
    parts.append(f"/* === {logical} === */\n{text.strip()}\n")

concat = "\n".join(parts)
mini = minify(concat)
header = (
    "/* AUTO-GENERATED by tools/css/build-critical-article-bundle.sh — DO NOT EDIT.\n"
    " * Source of truth: individual CSS files (article-css-priority.json +\n"
    " * PageHtmlBuilder.criticalStyleSheetAssets order).\n"
    " */\n"
)
out_path = root / "shared/css/critical-article.min.css"
out_path.write_text(header + mini + "\n", encoding="utf-8")
mini_bytes = len((header + mini + "\n").encode("utf-8"))

# Coverage: every source selector token appears in the unminified concat.
missing = []
for logical, path in sources:
    text = path.read_text(encoding="utf-8")
    for m in re.finditer(r"[.#][A-Za-z_][\w-]*", text):
        tok = m.group(0)
        if tok not in concat:
            missing.append(f"{logical}:{tok}")
            if len(missing) >= 10:
                break
    if len(missing) >= 10:
        break

report = {
    "out": str(out_path.relative_to(root)),
    "raw_bytes": raw_bytes,
    "min_bytes": mini_bytes,
    "saved_bytes": raw_bytes - mini_bytes,
    "saved_pct": round(100.0 * (raw_bytes - mini_bytes) / raw_bytes, 2) if raw_bytes else 0,
    "sha256": hashlib.sha256(out_path.read_bytes()).hexdigest(),
    "coverage_ok": len(missing) == 0,
    "missing": missing,
    "count": len(sources),
}
print(json.dumps(report, indent=2))
if missing:
    sys.exit(2)
PY
